title: Site

columns:
  - width: 1/2
    sections:
      pages:
        type: pages
        label: Main Pages
        templates:
          - about
          - designers
          - default

  - width: 1/2
    sections:
      dashboard_designers:
        type: pages
        label: Featured Designers (Quick Access)
        parent: site.find("designers")
        template: designer
        limit: 5
        layout: cards
        image:
          query: page.cover.toFile
          ratio: 1/1
          cover: true

      social_media:
        type: fields
        label: Site Social Media
        fields:
          social_linkedin:
            label: LinkedIn URL
            type: url
            icon: linkedin
          social_instagram:
            label: Instagram URL
            type: url
            icon: instagram
          social_youtube:
            label: YouTube URL
            type: url
            icon: youtube
          social_tiktok:
            label: TikTok URL
            type: url
            icon: video
          social_threads:
            label: Threads URL
            type: url
            icon: at-sign
          social_twitter:
            label: X (Twitter) URL
            type: url
            icon: twitter
